language: python
python:
  - '3.7'

branches:
  only:
    - staging

before_script:
  - pip install -r requirements/dev.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
