# Generated by Django 2.2.5 on 2019-09-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ancient_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancient_product', to='products.Product')),
                ('new_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product', to='products.Product')),
            ],
        ),
    ]
