# Generated by Django 2.2.10 on 2020-04-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_favorite_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='ancient_product_id',
            new_name='ancient_product',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='new_product_id',
            new_name='new_product',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
    ]
