# Generated by Django 2.2.10 on 2020-04-30 15:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20191023_1436'),
        ('favorites', '0003_auto_20200429_1704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'new_product', 'ancient_product')},
        ),
    ]
